# Generated by Django 6.0 on 2026-02-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
