# Generated by Django 6.0 on 2026-05-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management_app', '0003_alter_video_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(default='none', max_length=500),
        ),
    ]
