# Generated by Django 6.0 on 2026-05-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management_app', '0004_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(default='none', upload_to='thumbnails/'),
        ),
    ]
