# Generated by Django 6.0 on 2026-06-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management_app', '0005_alter_video_category_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(default='static/images/Logo.png', upload_to='thumbnails/'),
        ),
    ]
