# Generated by Django 6.0 on 2026-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_management_app', '0006_alter_video_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.ImageField(default='images/Logo.png', upload_to='thumbnails/'),
        ),
    ]
